### ISSUE TITLE
iPhone X + Rotor Riot Controller

### ISSUE THREAD

**Issue by syto203** [lechium/PUBC#2]
there are multiple issues so here is a list to keep track.
tested release (1.3-5)
1. Quickly pressing any button triggers the menu
2. You cant keep L2 pressed down and use R2
3. You cant keep Any Trigger(L1/L2/R1/R2) pressed Down and move the right joystick.
4. setting the aim for the L2 causes the aim to remain pressed down.

**Comment by lechium** [comment]
sorry i didnt respond earlier, i just saw this issue opened. ill have to test things out with rotor riot and see if i can replicate these issues.

**Comment by syto203** [comment]
#1 was fixed in latest. #4 got better but still hangs sometimes

**Comment by lechium** [comment]
ah the right joystick issue is likely related to whether or not you have my experimental
joystick support enabled for it. the initial
right joystick implementation is handled by the pubg mobile developers. if they dont work in tandem im not certain theres anything i can do to fix it.

**Comment by syto203** [comment]
The experimental support is essentially non playable as it causes fast unpredictable snaps of movements i.e: moving the joystick to the right direction immediately looks up or down.

**Comment by lechium** [comment]
everything should be significantly better now, i think all of these issues have been addressed. feel free to re-open if you don't think that is true after trying the latest version.
